### ISSUE TITLE
ENOENT error

### ISSUE THREAD

**Issue by Manaus** [agudulin/gulp-dart#6]
Hello,  
when trying to transpile dart to js I get this error: 

```
events.js:85
throw er; // Unhandled 'error' event
            ^
Error: spawn dart2js ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
  at child_process.js:1137:20
  at process._tickCallback (node.js:355:11)
```

My gulpfile is pretty simple: 

```
gulp.task 'default', ->
    gulp.src files.source
    .pipe watch(files.source)   
    .pipe plumber()
    .pipe dart()
    .pipe gulp.dest files.destin
```

Thanks for any suggestion

**Comment by agudulin** [comment]
Hi,

Looks like you don't have dartsdk installed. If you use brew try this help: https://www.dartlang.org/downloads/mac.html

Also don't forget to create a directory that you are passing as `dest` parameter.

**Comment by joseluis** [comment]
The same happened to me. If you are in Debian, Ubuntu or Mint, and you have already installed the dart package, you will have to manually add `/usr/lib/dart/bin` to the PATH ([source](https://github.com/dart-lang/sdk/issues/19926)).

e.g. Add this line at the end of your ~/.bashrc

```
export PATH="$PATH:/usr/lib/dart/bin"
```

**Comment by agudulin** [comment]
Thank you @joseluis. I am going to update the readme file then.
